version: '3.3'
services:
  duplicacy:
    image: nelsondane/duplicacy-docker:latest
    # build: .
    container_name: duplicacy
    restart: always
    ports:
      - 3875:3875
    hostname: duplicacy-web-docker
    environment:
      - MACHINE_ID=
    volumes:
      - /path/to/config:/root/.duplicacy-web
      - /path/to/data:/data
